name: "Static Analysis"

on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: "Static Analysis"
    continue-on-error: true # Continue on error to allow all jobs to complete
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-analysis-composer-${{ hashFiles('composer.lock') }}"
          path: 'vendor'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Run static analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --error-format=github